server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgre
    hikari:
      schema: warehouse
  flyway:
    table: flyway_schema_history_warehouse
    baseline-on-migrate: true
    locations: db.migration
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect

